### ISSUE TITLE
有没有dragOver事件

### ISSUE THREAD

**Issue by SunXinFei** [Foveluy/Dragact#10]
我看到api中没有dragOver事件，现在有一种需求就是跟手机桌面app一样，有一些应用和大小不一的小部件，不想拖拽排版，这个插件可以满足，但是手机桌面还有一种是应用之间拖拽可以创建文件夹。
_--------------------_
看了下until里面的源码和React-Grid-Layout的源码，发现原来用的是碰撞检测，具体的代码布局的思想能不能表述下。

**Comment by SunXinFei** [comment]
参考了React-Grid-Layout和Dragact 的源码 几个月前自己实现了一个跨组拖拽的网格布局 [react-grid-layout-between](https://github.com/SunXinFei/react-grid-layout-between) ，表示感谢

**Comment by Foveluy** [comment]
@SunXinFei 谢谢支持
