### ISSUE TITLE
能否提供参数禁止拖拽

### ISSUE THREAD

**Issue by welkink** [Foveluy/Dragact#25]
能否提供参数禁止拖拽

**Comment by Foveluy** [comment]
@welkink https://github.com/Foveluy/Dragact/blob/master/example/StaticWidget/index.tsx 这里有个静态布局的例子

**Comment by welkink** [comment]
谢谢





在 2018-08-28 08:53:44，"ZhengFang" <notifications@github.com> 写道：


@welkinkhttps://github.com/Foveluy/Dragact/blob/master/example/StaticWidget/index.tsx 这里有个静态布局的例子
