### ISSUE TITLE
babelrc 的一点点小建议

### ISSUE THREAD

**Issue by zhujinxuan** [Foveluy/Dragact#8]
1. 似乎 babel-preset-es2015 是一个比较过期的解决方案，也许可以考虑 babel-preset-env 
2.似乎可以考虑在默认的情况下不添加 react-hot-loader, transform-runtime，把这两个放在 test 和 webpack 两个 env 似乎比较适合；因为这两个会在 prod 的 bundle 中加入一些不必要的东西

下个月我可能会研究一下 rollup + ts 然后过来提 pr

**Comment by Foveluy** [comment]
@zhujinxuan 改了
